### Homework 3 Numpy Arrays

1. Open `cars.csv` in jupyter and look at the data. (Double click `cars.csv` to open in a new tab).
2. We are converting each **column** into an numpy array.
3. Notice we have text, integer and float data. 
4. Take care not to overwrite your starter code.

In [2]:
#Starter code. Do NOT modify this cell
import pandas as pd
import numpy as np

# Read in dataset
df = pd.read_csv('cars.csv',delimiter=';')

# Convert each column to an np.array
car = df.Car.to_numpy()
mpg = df.MPG.to_numpy()
cylinders = df.Cylinders.to_numpy()
displacement = df.Displacement.to_numpy()
horsepower = df.Horsepower.to_numpy()
weight = df.Weight.to_numpy()
acceleration = df.Acceleration.to_numpy()
model = df.Model.to_numpy()
origin = df.Origin.to_numpy()

# create an array of headers
headers = np.array(['Car', 'MPG', 'Cylinders', 'Displacement', 'Horsepower', 'Weight','Acceleration', 'Model', 'Origin'])


# 1. How can you get help on `np.array`?

Call `dir()` on `np.array`. 

Call `dir()` on `car`.

Note the difference. `car` has methods and attributes we can use.

In [5]:
help(np.array)
dir(np.array)
dir(car)


Help on built-in function array in module numpy:

array(...)
    array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K', 'A', 'C', 'F'}, optional
        Specify the memory layout of the array. If object is not an array, the
        newly c

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

2. What are the numpy datatypes for the `car`,`mpg`, `horsepower` and `origin` arrays? (Hint: Not `type(car)` and use `print()` to print the numpy type.)

In [12]:
#we can use dtype to get the data type of an array object
print(car.dtype, mpg.dtype, horsepower.dtype, origin.dtype)

object float64 float64 object


3. `numpy` is often imported as `np`. What is this action called? Why might you do this? 

In [ ]:
# it's called that NumPy is imported under the np alias. We can create alias when using "as" keyword when importing
#So that later in our code we can refer to numpy as just "np". So it's makes it easier to use it.

4. Each of the arrays (cars, mpg, cylinders, etc..) has how many dimensions? Show how to find this using code. 

In [22]:
#We can use the ndim attribute that returns an integer that tells us how many dimensions the array have.
print(car.ndim)
print(mpg.ndim)
print(cylinders.ndim)
print(displacement.ndim)
print(horsepower.ndim)
print(weight.ndim)
print(acceleration.ndim)
print(model.ndim)
print(origin.ndim)
# so they are all 1-dimentional

1
1
1
1
1
1
1
1
1


5. Show how to:

- multiply the `mpg` array by 12.
- divide the `mpg` array by 3.
- raise the `mpg` array to the power of 4.
- take the square root of the `mpg` array.

In [34]:
mpg*12 #multiply the mpg array by 12
mpg/3 #divide the mpg array by 3
mpg ** 4 #raise the mpg array to the power of 4
np.sqrt(mpg)#take the square root of the mpg array

array([4.24264069, 3.87298335, 4.24264069, 4.        , 4.12310563,
       3.87298335, 3.74165739, 3.74165739, 3.74165739, 3.87298335,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       3.87298335, 3.74165739, 0.        , 3.87298335, 3.74165739,
       4.89897949, 4.69041576, 4.24264069, 4.58257569, 5.19615242,
       5.09901951, 5.        , 4.89897949, 5.        , 5.09901951,
       4.58257569, 3.16227766, 3.16227766, 3.31662479, 3.        ,
       5.19615242, 5.29150262, 5.        , 5.        , 0.        ,
       4.35889894, 4.        , 4.12310563, 4.35889894, 4.24264069,
       3.74165739, 3.74165739, 3.74165739, 3.74165739, 3.46410162,
       3.60555128, 3.60555128, 4.24264069, 4.69041576, 4.35889894,
       4.24264069, 4.79583152, 5.29150262, 5.47722558, 5.47722558,
       5.56776436, 5.91607978, 5.19615242, 5.09901951, 4.89897949,
       5.        , 4.79583152, 4.47213595, 4.58257569, 3.60555128,
       3.74165739, 3.87298335, 3.74165739, 4.12310563, 3.31662

6. What is the ___ of `horsepower`?
- sum
- min
- max
- median
- Optional: mode (May need to google help)

In [11]:
print(horsepower.sum())
print(horsepower.min())
print(horsepower.max())
print(np.median(horsepower))
from statistics import mode
mode(horsepower)

42033.0
0.0
230.0
93.5


150.0

7. Select a subset of `acceleration`. 

- Select only the first 5 elements.
- Select every other element (new selection).

In [55]:
acceleration #select acceleration
acceleration[0:5] #Select only the first 5 elements
acceleration[::2] #Select every other element

array([12. , 11. , 10.5,  9. , 10. , 17.5, 11. , 11. ,  8. ,  9.5, 15. ,
       15.5, 14.5, 17.5, 17.5, 15. , 15. , 18.5, 15.5, 19. , 13. , 15.5,
       15.5, 11.5, 13. , 12. , 13.5, 15. , 14. , 19.5, 19. , 19. , 15.5,
       23.5, 16.5, 12. , 13. , 11. , 13.5, 13.5, 14. , 14. , 18. , 18. ,
       17. , 15. , 13. , 13. , 12.5, 12. , 14.5, 11. , 16.5, 16. , 16. ,
       14. , 13. , 15. , 19.5, 13.5, 14. , 13. , 19.5, 14. , 11. , 13.5,
       16.5, 16. , 19. , 21. , 17. , 16.5, 14.5, 16. , 16.5, 14.5, 19. ,
       15.5, 15. , 16. , 16. , 19.5, 14. , 13.5, 18.5, 19. , 13.5, 16. ,
       16. , 13.5, 17. , 14. , 15. , 14.5, 17.5, 16.9, 17.7, 13. , 13.9,
       15.4, 17.6, 22.2, 14.2, 17.7, 16.2, 12.2, 16.4, 15.7, 21.9, 16.7,
       12. , 14. , 14.8, 15.5, 12.5, 13.7, 16.4, 17.7, 11.1, 12.2, 14.5,
       18.2, 17. , 16.4, 14.5, 13.5, 14.4, 18.6, 15.5, 12.8, 18.2, 15.4,
       17.2, 16.7, 15.1, 13.4, 13.7, 14.2, 14.5, 16.7, 14.9, 13.6, 15.8,
       16.6, 18.2, 18.2, 15.4, 13.2, 14.9, 15. , 14

8. Show how to select the number `99` in the array below. 

In [58]:
select_99 = np.array([[1,2,3],
                      [4,5,99]])

In [62]:
print(select_99[1,2])

99


9. Select the last element in each subarray (do this with one operation.)

In [63]:
select_more = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
# returns array([3, 6, 9])

In [67]:
print(select_more[0:3,2])

[3 6 9]


10. Use the built-in `np.lookfor()` function to search for `'log'`.

Use the function you find and apply it to `mpg`.

In [81]:
np.lookfor('log')
np.log(mpg) # returns natural logarithm of mpg

Search results for 'log'
------------------------
numpy.log
    Natural logarithm, element-wise.
numpy.log2
    Base-2 logarithm of `x`.
numpy.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.log1p
    Return the natural logarithm of one plus the input array, element-wise.
numpy.logspace
    Return numbers spaced evenly on a log scale.
numpy.logaddexp
    Logarithm of the sum of exponentiations of the inputs.
numpy.logaddexp2
    Logarithm of the sum of exponentiations of the inputs in base-2.
numpy.logical_or
    Compute the truth value of x1 OR x2 element-wise.
numpy.logical_and
    Compute the truth value of x1 AND x2 element-wise.
numpy.logical_not
    Compute the truth value of NOT x element-wise.
numpy.logical_xor
    Compute the truth value of x1 XOR x2, element-wise.
numpy.ma.log
    Natural logarithm, element-wise.
numpy.ma.log2
    Base-2 logarithm of `x`.
numpy.ma.log10
    Return the base 10 logarithm of the input array, element-wise.
numpy.rec

array([2.89037176, 2.7080502 , 2.89037176, 2.77258872, 2.83321334,
       2.7080502 , 2.63905733, 2.63905733, 2.63905733, 2.7080502 ,
             -inf,       -inf,       -inf,       -inf,       -inf,
       2.7080502 , 2.63905733,       -inf, 2.7080502 , 2.63905733,
       3.17805383, 3.09104245, 2.89037176, 3.04452244, 3.29583687,
       3.25809654, 3.21887582, 3.17805383, 3.21887582, 3.25809654,
       3.04452244, 2.30258509, 2.30258509, 2.39789527, 2.19722458,
       3.29583687, 3.33220451, 3.21887582, 3.21887582,       -inf,
       2.94443898, 2.77258872, 2.83321334, 2.94443898, 2.89037176,
       2.63905733, 2.63905733, 2.63905733, 2.63905733, 2.48490665,
       2.56494936, 2.56494936, 2.89037176, 3.09104245, 2.94443898,
       2.89037176, 3.13549422, 3.33220451, 3.40119738, 3.40119738,
       3.4339872 , 3.55534806, 3.29583687, 3.25809654, 3.17805383,
       3.21887582, 3.13549422, 2.99573227, 3.04452244, 2.56494936,
       2.63905733, 2.7080502 , 2.63905733, 2.83321334, 2.39789

11. You your google skills to find the unique items in `origin`. (This may not have been covered in the readings.)

In [70]:
np.unique(origin)


array(['Europe', 'Japan', 'US'], dtype=object)

12. 
- Create a 2D array and print its shape as well as ndim. (Any shape is fine)

- Create a 3D array and print its shape as well as ndim.

- Create a 4D array and print its shape as well as ndim. *It's hard to visualize 4-Dimensions but numpy can do it with ease!*

In [10]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]]) #2D array

print(a)
print(a.shape, a.ndim)

b = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]]) #3D array

print(b)
print(b.shape, b.ndim)

c = np.array([1, 2, 3, 4], ndmin=4)
print(c)
print(c.shape, c.ndim)


[[[[1 2 3 4]]]]
(1, 1, 1, 4) 4


13.Use boolean indexing to create an array of `True/False` using `origin` and the value 'US'.

In [32]:
filter_view = origin == 'US'
#newArray = origin[filter_view]
#print(newArray)

(254,)


14. Apply your index (from above) to the `car` array. You should now only see cars that are of US origin. 

In [35]:
carsArray = car[filter_view]
print(carsArray)

['Chevrolet Chevelle Malibu' 'Buick Skylark 320' 'Plymouth Satellite'
 'AMC Rebel SST' 'Ford Torino' 'Ford Galaxie 500' 'Chevrolet Impala'
 'Plymouth Fury iii' 'Pontiac Catalina' 'AMC Ambassador DPL'
 'Chevrolet Chevelle Concours (sw)' 'Ford Torino (sw)'
 'Plymouth Satellite (sw)' 'AMC Rebel SST (sw)' 'Dodge Challenger SE'
 "Plymouth 'Cuda 340" 'Ford Mustang Boss 302' 'Chevrolet Monte Carlo'
 'Buick Estate Wagon (sw)' 'Plymouth Duster' 'AMC Hornet' 'Ford Maverick'
 'AMC Gremlin' 'Ford F250' 'Chevy C20' 'Dodge D200' 'Hi 1200D'
 'Chevrolet Vega 2300' 'Ford Pinto' 'AMC Gremlin'
 'Plymouth Satellite Custom' 'Chevrolet Chevelle Malibu' 'Ford Torino 500'
 'AMC Matador' 'Chevrolet Impala' 'Pontiac Catalina Brougham'
 'Ford Galaxie 500' 'Plymouth Fury iii' 'Dodge Monaco (sw)'
 'Ford Country Squire (sw)' 'Pontiac Safari (sw)'
 'AMC Hornet Sportabout (sw)' 'Chevrolet Vega (sw)' 'Pontiac Firebird'
 'Ford Mustang' 'Mercury Capri 2000' 'Plymouth Cricket'
 'Dodge Colt Hardtop' 'Chevrolet Vega' 'Ford

**The remaining questions are OPTIONAL**: The readings did not address all of these so you may have to use some "Google-Fu". 

1.What is an identity matrix? 
Create an identiy matrix of size 5 using an np method. 

2. Transpose the following array. 

In [ ]:
transpose_me = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])


3. Why does this multiplication operation fail? 

In [ ]:
arr1 = np.array([[1,2,3],
                      [4,5,6],
                      [7,8,9]])
arr2 = np.array([[1,2,3],
                      [4,5,6]])

arr1 * arr2

Use numpy to answer the following questions. 

4. What is the average horsepower for `Europe` cars? (Hint: create boolean index of 'US' apply it to horsepower and perform the calculation.)

5. On average are Japanse cars more fuel efficient than US cars? 

6. What is the correlation coefficient of `mpg` and `weight`?

7. Why might you prefer an `np.array()` over a Python `list`? And when is a Python `list` preferred? 